apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - checkout-service-deployment.yml
  - checkout-service.yml

commonLabels:
  app: checkout-service
  project: slipper-shop
  managed-by: argocd

namespace: checkout-service