apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
      - name: checkout-api
        image: oleschmid/slipper-shop-checkout-service:latest
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"