apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - product-service-deployment.yml
  - product-service.yml

commonLabels:
  app: product-service
  project: slipper-shop
  managed-by: argocd

namespace: product-service