apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  labels:
    app: checkout-service
    project: slipper-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
      - name: checkout-api
        image: oleschmid/slipper-shop-checkout-service:latest
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  type: ClusterIP
  selector:
    app: checkout-service
  ports:
    - port: 80
      targetPort: 8083