apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkout-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Terikyy/devops-lecture-project
    targetRevision: HEAD
    path: kubernetes/checkout-service
  destination:
    server: https://kubernetes.default.svc
    namespace: checkout-service
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
