apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-tempo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.10.3
      helm:
        valueFiles:
          - $values/kubernetes/monitoring/tempo/values.yml
    - repoURL: https://github.com/Terikyy/devops-lecture-project
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
